// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("MzLiteFSharp.SQL")>]
[<assembly: AssemblyProductAttribute("MzLiteFSharp")>]
[<assembly: AssemblyDescriptionAttribute("F# port of MzLite")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "MzLiteFSharp.SQL"
    let [<Literal>] AssemblyProduct = "MzLiteFSharp"
    let [<Literal>] AssemblyDescription = "F# port of MzLite"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
