// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("MzIO.Bruker")>]
[<assembly: AssemblyProductAttribute("MzIO")>]
[<assembly: AssemblyDescriptionAttribute("Generic data model to unify various reader and writer for different formats used in protein mass spectrometry")>]
[<assembly: AssemblyVersionAttribute("0.0.6")>]
[<assembly: AssemblyFileVersionAttribute("0.0.6")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "MzIO.Bruker"
    let [<Literal>] AssemblyProduct = "MzIO"
    let [<Literal>] AssemblyDescription = "Generic data model to unify various reader and writer for different formats used in protein mass spectrometry"
    let [<Literal>] AssemblyVersion = "0.0.6"
    let [<Literal>] AssemblyFileVersion = "0.0.6"
    let [<Literal>] AssemblyConfiguration = "Release"
